/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ufjf.view;

/**
 *
 * @author vitorfs
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnDistribuidoras = new javax.swing.JButton();
        btnFilmes = new javax.swing.JButton();
        btnItens = new javax.swing.JButton();
        mainPane = new javax.swing.JScrollPane();
        menuLocadora = new javax.swing.JMenuBar();
        mnArquivo = new javax.swing.JMenu();
        mnSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ufjf/images/play.png"))); // NOI18N
        jButton1.setText("Locação");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMaximumSize(new java.awt.Dimension(90, 54));
        jButton1.setMinimumSize(new java.awt.Dimension(90, 54));
        jButton1.setPreferredSize(new java.awt.Dimension(90, 54));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ufjf/images/users.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setFocusable(false);
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.setMaximumSize(new java.awt.Dimension(90, 54));
        btnClientes.setMinimumSize(new java.awt.Dimension(90, 54));
        btnClientes.setPreferredSize(new java.awt.Dimension(90, 54));
        btnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnClientes);

        btnDistribuidoras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ufjf/images/shopping_cart.png"))); // NOI18N
        btnDistribuidoras.setText("Distribuidoras");
        btnDistribuidoras.setFocusable(false);
        btnDistribuidoras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDistribuidoras.setMaximumSize(new java.awt.Dimension(90, 54));
        btnDistribuidoras.setMinimumSize(new java.awt.Dimension(90, 54));
        btnDistribuidoras.setPreferredSize(new java.awt.Dimension(90, 54));
        btnDistribuidoras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDistribuidoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDistribuidorasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDistribuidoras);

        btnFilmes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ufjf/images/television.png"))); // NOI18N
        btnFilmes.setText("Filmes");
        btnFilmes.setFocusable(false);
        btnFilmes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFilmes.setMaximumSize(new java.awt.Dimension(90, 54));
        btnFilmes.setMinimumSize(new java.awt.Dimension(90, 54));
        btnFilmes.setPreferredSize(new java.awt.Dimension(90, 54));
        btnFilmes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilmesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFilmes);

        btnItens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ufjf/images/new_page.png"))); // NOI18N
        btnItens.setText("Itens");
        btnItens.setFocusable(false);
        btnItens.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnItens.setMaximumSize(new java.awt.Dimension(90, 54));
        btnItens.setMinimumSize(new java.awt.Dimension(90, 54));
        btnItens.setPreferredSize(new java.awt.Dimension(90, 54));
        btnItens.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItensActionPerformed(evt);
            }
        });
        jToolBar1.add(btnItens);

        mainPane.setBorder(null);

        mnArquivo.setText("Arquivo");
        menuLocadora.add(mnArquivo);

        mnSobre.setText("Sobre");
        menuLocadora.add(mnSobre);

        setJMenuBar(menuLocadora);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jToolBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(mainPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(mainPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-800)/2, (screenSize.height-622)/2, 800, 622);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        if (!(mainPane.getViewport().getView() instanceof PanelClientes)) {
            mainPane.setViewportView(new PanelClientes());
        }
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnDistribuidorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDistribuidorasActionPerformed
        if (!(mainPane.getViewport().getView() instanceof PanelDistribuidoras)) {
            mainPane.setViewportView(new PanelDistribuidoras());
        }
    }//GEN-LAST:event_btnDistribuidorasActionPerformed

    private void btnFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilmesActionPerformed
        if (!(mainPane.getViewport().getView() instanceof PanelFilmes)) {
            mainPane.setViewportView(new PanelFilmes());
        }
    }//GEN-LAST:event_btnFilmesActionPerformed

    private void btnItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItensActionPerformed
        if (!(mainPane.getViewport().getView() instanceof PanelItens)) {
            mainPane.setViewportView(new PanelItens());
        }
    }//GEN-LAST:event_btnItensActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnDistribuidoras;
    private javax.swing.JButton btnFilmes;
    private javax.swing.JButton btnItens;
    private javax.swing.JButton jButton1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JScrollPane mainPane;
    private javax.swing.JMenuBar menuLocadora;
    private javax.swing.JMenu mnArquivo;
    private javax.swing.JMenu mnSobre;
    // End of variables declaration//GEN-END:variables
}
